on:
  workflow_dispatch:
  push:
    branches: main

name: Analyze Repository

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          upgrade: 'TRUE'
          packages:
            any::remotes
            any::rmarkdown
            any::dplyr
            any::git2r

      - name: Install chchchanges
        run: |
          Rscript -e 'remotes::install_github("beanumber/chchchanges")'

      # Render READEME.md using rmarkdown
      - name: render README
        run: |
          Rscript -e 'rmarkdown::render("quarto-manuscript/README.Rmd", output_format = "md_document")'
  
      - name: commit rendered README
        run: |
          git add README.md man/figures/README-*
          git commit -m "Re-build README.md" || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
